plugins {
    id 'application'
}

group = "com.hivemq"
description = "HiveMQ CE is a Java-based open source MQTT broker that fully supports MQTT 5"

repositories {
    mavenCentral()
}

dependencies {
    // netty
    implementation(libs.netty.buffer)
    implementation(libs.netty.codec)
    implementation(libs.netty.codec.http)
    implementation(libs.netty.common)
    implementation(libs.netty.handler)
    implementation(libs.netty.transport)

    // logging
    implementation(libs.slf4j.api)
    implementation(libs.julToSlf4j)
    implementation(libs.logback.classic)

    // security
    implementation(libs.bouncycastle.prov)
    implementation(libs.bouncycastle.pkix)

    // persistence
    implementation(libs.xodus.openApi)
    implementation(libs.xodus.environment)

    // config
    implementation(libs.jaxb.api)
    runtimeOnly(libs.jaxb.impl)

    // metrics
    implementation(libs.dropwizard.metrics)
    implementation(libs.dropwizard.metrics.jmx)
    runtimeOnly(libs.dropwizard.metrics.logback)
    implementation(libs.guice)
    implementation(libs.javax.annotation.api)

    // common
    implementation(libs.jctools)

    implementation(libs.jetbrains.annotations)

    /* ******************** test ******************** */
    testImplementation(libs.junit)
    testImplementation(libs.mockito)
    testImplementation(libs.equalsVerifier)
    testImplementation(libs.concurrentUnit)
    testImplementation(libs.shrinkwrap.api)
    testRuntimeOnly(libs.shrinkwrap.impl)
    testImplementation(libs.wiremock.jre8.standalone)
    testImplementation(libs.javassist)
    testImplementation(libs.awaitility)
    testImplementation(libs.jetbrains.annotations)
}

application {
    mainClass = 'com.hivemq.Main'
    applicationDefaultJvmArgs = ['-Xmx2G', '-Xms2G', '-server', '-Dfile.encoding=UTF-8',
                                 '--add-opens',
                                 'java.base/java.lang=ALL-UNNAMED',
                                 '--add-opens',
                                 'java.base/java.nio=ALL-UNNAMED',
                                 '--add-opens',
                                 'java.base/sun.nio.ch=ALL-UNNAMED',
                                 '--add-opens',
                                 'jdk.management/com.sun.management.internal=ALL-UNNAMED',
                                 '--add-exports',
                                 'java.base/jdk.internal.misc=ALL-UNNAMED',
                                 '-Djava.net.preferIPv4Stack=true',
                                 '-Dcom.sun.management.jmxremote', '-Dcom.sun.management.jmxremote.port=9010', '-Dcom.sun.management.jmxremote.local.only=false', '-Dcom.sun.management.jmxremote.authenticate=false', '-Dcom.sun.management.jmxremote.ssl=false', '-noverify']
}

wrapper {
    gradleVersion = '8.10.2'
}
