[versions]
apache-commonsLang = "3.14.0"
awaitility = "4.2.2"
bouncycastle = "1.78.1"
concurrentUnit = "0.4.6"
dropwizard-metrics = "4.2.28"
equalsVerifier = "3.16.2"
guice = "5.1.0"
javassist = "3.30.2-GA"
javax-annotation-api = "1.3.2"
jaxb-api = "2.3.3"
jaxb-impl = "2.3.9"
jctools = "4.0.5"
jetbrainsAnnotations = "26.0.1"
junit = "4.13.2"
logback = "1.5.12"
mockito = "5.11.0"
netty = "4.1.114.Final"
shrinkwrap = "1.2.6"
slf4j = "2.0.16"
wiremock = "3.0.1"
xodus = "1.2.3"

[libraries]
apache-commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commonsLang" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
dropwizard-metrics = { module = "io.dropwizard.metrics:metrics-core", version.ref = "dropwizard-metrics" }
dropwizard-metrics-jmx = { module = "io.dropwizard.metrics:metrics-jmx", version.ref = "dropwizard-metrics" }
dropwizard-metrics-logback = { module = "io.dropwizard.metrics:metrics-logback", version.ref = "dropwizard-metrics" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation-api" }
jaxb-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jaxb-api" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "jaxb-impl" }
jctools = { module = "org.jctools:jctools-core", version.ref = "jctools" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
julToSlf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }
netty-common = { module = "io.netty:netty-common", version.ref = "netty" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
netty-transport = { module = "io.netty:netty-transport", version.ref = "netty" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
xodus-environment = { module = "org.jetbrains.xodus:xodus-environment", version.ref = "xodus" }
xodus-openApi = { module = "org.jetbrains.xodus:xodus-openAPI", version.ref = "xodus" }
# test
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
concurrentUnit = { module = "net.jodah:concurrentunit", version.ref = "concurrentUnit" }
equalsVerifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsVerifier" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
shrinkwrap-api = { module = "org.jboss.shrinkwrap:shrinkwrap-api", version.ref = "shrinkwrap" }
shrinkwrap-impl = { module = "org.jboss.shrinkwrap:shrinkwrap-impl-base", version.ref = "shrinkwrap" }
wiremock-jre8-standalone = { module = "com.github.tomakehurst:wiremock-jre8-standalone", version.ref = "wiremock" }
